package edu.kmaooad.constants.bot;

public enum ConversationState {
    // Common
    CONVERSATION_STARTED,
    WAITING_FOR_CHOICE,
    WAITING_FOR_TEXT,
    WAITING_FOR_MAIN_MENU_ACTION_CHOICE,

    // Group
    WAITING_FOR_GROUP_ACTION_CHOICE,
    WAITING_FOR_GROUP_ADD_ACTION,
    ASK_FOR_GROUP_ID,
    ASK_FOR_GROUP_NAME,
    ASK_FOR_GROUP_GRADE,
    ASK_FOR_GROUP_YEAR,
    WAITING_FOR_GROUP_NAME,
    WAITING_FOR_GROUP_GRADE,
    WAITING_FOR_GROUP_YEAR,
    WAITING_FOR_GROUP_ID,

    // Assign
    WAITING_FOR_GROUP_ACTIVITY_ASSIGN_CHOICE,
    WAITING_FOR_GROUP_TO_ASSIGN_CHOICE,
    WAITING_FOR_STUDENT_ACTIVITY_ASSIGN_CHOICE,
    WAITING_FOR_STUDENT_TO_ASSIGN_CHOICE,

    // Templates
    WAITING_FOR_TEMPLATE_ACTION_CHOICE,
    ASK_FOR_TEMPLATE_ID,
    ASK_FOR_TEMPLATE_NAME,
    ASK_FOR_TEMPLATE_GRADE,
    ASK_FOR_TEMPLATE_YEAR,
    WAITING_FOR_TEMPLATE_ID,
    WAITING_FOR_TEMPLATE_NAME,
    WAITING_FOR_TEMPLATE_GRADE,
    WAITING_FOR_TEMPLATE_YEAR,

    // CSV
    WAITING_FOR_STUDENT_ACTION_CHOICE, WAITING_FOR_STUDENT_CSV
}
