package edu.kmaooad.constants.bot;

public enum ConversationState {
    CONVERSATION_STARTED,
    WAITING_FOR_CHOICE,
    WAITING_FOR_TEXT,

    WAITING_FOR_GROUP_ACTION_CHOICE,
    WAITING_FOR_GROUP_ADD_ACTION,
    WAITING_FOR_GROUP_NAME,
    WAITING_FOR_GROUP_GRADE,
    WAITING_FOR_GROUP_YEAR,
    WAITING_FOR_GROUP_ID,
}
